branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: boilermake-2017-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  profile: null
  repository: null
  sc: git
